from typing import Protocol


class Settings(Protocol):
    def read(self) -> dict[str, str]: ...

    async def apply(self, updates: dict[str, str], user: str) -> list: ...


class VersionStore(Protocol):
    def draft(self) -> dict | None: ...

    def save_draft(self, data: dict | None) -> None: ...

    def versions(self) -> list[dict]: ...

    def append(self, data: dict) -> dict: ...


class Verifier(Protocol):
    async def confirm(self, user: str, password: str, ip: str) -> bool: ...
