[env:atena_satellite_esp32s3]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
build_unflags = -std=gnu++11
build_flags =
    -std=gnu++17
    -D CORE_DEBUG_LEVEL=3
    -D WIFI_SSID=\"REPLACE_VIA_SCRIPT\"
    -D WIFI_PASS=\"REPLACE_VIA_SCRIPT\"
    -D ATENA_SUPERVISOR_URL=\"https://REPLACE_VIA_SCRIPT:8443\"
    -D ATENA_NODE_ID=\"REPLACE_VIA_SCRIPT\"
    -D ATENA_NODE_TOKEN=\"REPLACE_VIA_SCRIPT\"
    -D ATENA_EDGE_THRESHOLD=0.85
lib_deps =
    bblanchon/ArduinoJson @ ^7.2.0
test_ignore = *
