DEMO_AUTOMATIONS = [
    {"id": "1728000000001", "alias": "Luce cucina con il movimento", "description": "Accende la cucina quando entri e la spegne dopo 5 minuti senza movimento.",
     "mode": "restart",
     "triggers": [{"trigger": "state", "entity_id": "binary_sensor.movimento_cucina", "to": "on"}],
     "conditions": [{"condition": "sun", "after": "sunset", "before": "sunrise"}],
     "actions": [{"action": "light.turn_on", "target": {"entity_id": "light.luce_cucina"}, "data": {"brightness_pct": 70}},
                 {"wait_for_trigger": [{"trigger": "state", "entity_id": "binary_sensor.movimento_cucina", "to": "off",
                                        "for": {"minutes": 5}}]},
                 {"action": "light.turn_off", "target": {"entity_id": "light.luce_cucina"}}]},
    {"id": "1728000000002", "alias": "Buongiorno", "description": "Apre le tapparelle nei giorni feriali.",
     "mode": "single",
     "triggers": [{"trigger": "time", "at": "07:00:00"}],
     "conditions": [{"condition": "time", "weekday": ["mon", "tue", "wed", "thu", "fri"]}],
     "actions": [{"action": "cover.open_cover", "target": {"entity_id": ["cover.tapparella_soggiorno", "cover.tapparella_camera"]}}]},
    {"id": "1728000000003", "alias": "Porta aperta di notte", "description": "",
     "mode": "single",
     "triggers": [{"trigger": "state", "entity_id": "binary_sensor.porta_ingresso", "to": "on", "for": {"minutes": 2}}],
     "conditions": [{"condition": "time", "after": "23:00:00", "before": "06:00:00"}],
     "actions": [{"action": "notify.notify", "data": {"message": "La porta d'ingresso è aperta da 2 minuti"}}]},
]
